{
 "title": "API-RPC接口",
 "tags": [
  "API",
  "RPC"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(rpc_server_requests_code_total,namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(rpc_server_requests_duration_ms_bucket{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(rpc_server_requests_duration_ms_bucket{service=\"$service\", namespace=\"$namespace\"},method)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "全局维度", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "总请求量（$interval）",
   "type": "stat",
   "description": "过去 $interval 的$service总请求量",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_code_total{namespace=\"${namespace}\", service=\"$service\"}[$interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总错误数（$interval）",
   "type": "stat",
   "description": "过去 $interval 的$service请求错误数",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_code_total{namespace=\"${namespace}\", service=\"$service\",code!=\"0\"}[$interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "错误率%",
   "type": "gauge",
   "description": "过去 $interval 请求错误率",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(sum(increase(rpc_server_requests_code_total{namespace=\"${namespace}\",service=\"${service}\", code!=\"0\"}[$interval])) by (service) / sum(increase(rpc_server_requests_code_total{namespace=\"${namespace}\",service=\"${service}\"}[$interval])) by (service))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "最大QPS",
   "type": "stat",
   "description": "过去 $interval 内的最大（基于 1m 窗口平均的）QPS",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(\n  sum(rate(rpc_server_requests_duration_ms_count{namespace=\"${namespace}\", service=\"$service\"}[1m]))[$interval:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总接口数",
   "type": "stat",
   "description": "总接口数",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(increase(rpc_server_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\", code!=\"0\"}[1m] )) by (method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "【$service】RPC总请求",
   "type": "stat",
   "description": "记录的是服务启动以来的数据",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_server_requests_code_total{namespace=\"${namespace}\", service=\"${service}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rpc_client_requests_code_total{namespace=\"${namespace}\", service=\"${service}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "服务维度-$service（总体情况）- RPC-server ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "RPC Server 请求耗时分布【$interval】(ms)",
   "type": "bargauge",
   "description": "server 请求耗时分布，统计服务所有请求各个区间【$interval】的耗时分布，单位ms",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service, le) (increase(rpc_server_requests_duration_ms_bucket{namespace=\"${namespace}\", service=\"${service}\"}[$interval]))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "RPC Server接口请求延时热力图",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (increase(rpc_server_requests_duration_ms_bucket{namespace=\"${namespace}\", service=\"${service}\"}[$interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Server QPS",
   "type": "timeseries",
   "description": "${service} 所有 method 汇总QPS",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\" }[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "RPC Server 接口请求量($interval)",
   "type": "timeseries",
   "description": "接口请求量，$interval的维度进行统计",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_duration_ms_count{namespace=\"${namespace}\", service=\"${service}\"}[$interval])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Server 各接口 QPS （by Pod）",
   "type": "timeseries",
   "description": "${service} 各个 server method 的QPS",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\" }[5m])) by (method,pod)",
     "legendFormat": "{{method}} | {{pod}}"
    }
   ]
  },
  {
   "title": "RPC Server 各接口 QPS（by method）",
   "type": "timeseries",
   "description": "${service} 各个 server method 的QPS",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\" }[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "接口耗时P90",
   "type": "timeseries",
   "description": "计算 【$service】 服务中，每个 method 的 RPC 请求，在最近 5 分钟内的 P90 响应耗时（单位：毫秒）",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9,  sum by(service, method, le) (rate(rpc_server_requests_duration_ms_bucket{namespace=\"${namespace}\", service=\"${service}\"}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC Server P95 延迟（ms）",
   "type": "timeseries",
   "description": "95分位延迟",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum (rate(rpc_server_requests_duration_ms_bucket{namespace=\"${namespace}\",service=\"${service}\"}[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Server 请求数 (by Code)",
   "type": "timeseries",
   "description": "RPC Server 过去 $interval 请求数（按状态码分）",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_code_total{namespace=\"${namespace}\", service=\"${service}\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "RPC Server 平均耗时（ms）",
   "type": "timeseries",
   "description": "RPC 服务端请求的平均耗时",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_requests_duration_ms_sum{namespace=\"${namespace}\",service=\"${service}\"}[5m])) \n/ \nsum(rate(rpc_server_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\"}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "服务维度-$service（总体情况）- RPC-client ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }
  },
  {
   "title": "RPC Client 请求耗时分布【$interval】(ms)",
   "type": "bargauge",
   "description": "client 请求耗时分布，统计服务所有请求各个区间【$interval】的耗时分布，单位ms",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service,le) (increase(rpc_client_requests_duration_ms_bucket{namespace=\"${namespace}\", service=\"${service}\"}[$interval]))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "RPC Client接口请求延时热力图",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum by (le) (increase(rpc_client_requests_duration_ms_bucket{namespace=\"${namespace}\", service=\"${service}\"}[$interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Client QPS",
   "type": "timeseries",
   "description": "${service} 所有 method 汇总QPS",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\" }[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "RPC Client 接口请求量($interval)",
   "type": "timeseries",
   "description": "接口请求量，$interval的维度进行统计",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(increase(rpc_client_requests_duration_ms_count{namespace=\"${namespace}\", service=\"${service}\"}[$interval])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Client 各接口 QPS （by Pod）",
   "type": "timeseries",
   "description": "${service} 各个 client method 的QPS",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\" }[5m])) by (method,pod)",
     "legendFormat": "{{method}} | {{pod}}"
    }
   ]
  },
  {
   "title": "RPC Client 各接口 QPS （by method）",
   "type": "timeseries",
   "description": "${service} 各个 client method 的QPS",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\" }[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Client 平均耗时（ms）",
   "type": "timeseries",
   "description": "RPC 客户端请求的平均耗时",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_requests_duration_ms_sum{namespace=\"${namespace}\",service=\"${service}\"}[5m])) \n/ \nsum(rate(rpc_client_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\"}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "RPC Client P95 延迟（ms）",
   "type": "timeseries",
   "description": "95分位延迟",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum (rate(rpc_client_requests_duration_ms_bucket{namespace=\"${namespace}\",service=\"${service}\"}[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "接口维度-$service ($method)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "RPC Server 接口（$method）请求耗时分布【$interval】(ms) ",
   "type": "bargauge",
   "description": "server 请求耗时分布，统计服务所有请求各个区间【$interval】的耗时分布，单位ms",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service, le) (increase(rpc_server_requests_duration_ms_bucket{namespace=\"${namespace}\", service=\"${service}\", method=\"${method}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Client 接口（$method）请求耗时分布【$interval】(ms) ",
   "type": "bargauge",
   "description": "client 请求耗时分布，统计服务所有请求各个区间【$interval】的耗时分布，单位ms",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service,le) (increase(rpc_client_requests_duration_ms_bucket{namespace=\"${namespace}\", service=\"${service}\", method=\"${method}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Server 平均耗时（ms）",
   "type": "timeseries",
   "description": "RPC 服务端请求的平均耗时",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_requests_duration_ms_sum{namespace=\"${namespace}\",service=\"${service}\",method=\"${method}\"}[5m])) \n/ \nsum(rate(rpc_server_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\",method=\"${method}\"}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "RPC Server 每秒请求数率 (by Code)",
   "type": "timeseries",
   "description": "RPC Server 每秒请求速率（按状态码分）",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_requests_code_total{namespace=\"${namespace}\", service=\"${service}\", method=\"${method}\" }[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}