{
 "title": "API-HTTP接口",
 "tags": [
  "API",
  "HTTP"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_server_requests_code_total,namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(http_server_requests_duration_ms_bucket{namespace=\"$namespace\"},service)"
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(http_server_requests_duration_ms_bucket{service=\"$service\", namespace=\"$namespace\"},path)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "全局维度", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "总请求量（$interval）",
   "type": "stat",
   "description": "过去 $interval 的$service总请求量",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_code_total{namespace=\"${namespace}\", service=\"$service\"}[$interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总错误数（$interval）",
   "type": "stat",
   "description": "过去 $interval 的$service请求错误数",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_code_total{namespace=\"${namespace}\", service=\"$service\",code!=\"200\"}[$interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "错误率%",
   "type": "gauge",
   "description": "过去 $interval 请求错误率",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(sum(increase(http_server_requests_code_total{namespace=~\"${namespace}\",service=~\"${service}\", code!=\"200\"}[$interval])) by (service) / sum(increase(http_server_requests_code_total{namespace=\"${namespace}\",service=\"${service}\"}[$interval])) by (service))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "最大QPS",
   "type": "stat",
   "description": "过去 $interval 内的最大（基于 1m 窗口平均的）QPS",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(\n  sum(rate(http_server_requests_duration_ms_count{namespace=\"${namespace}\", service=\"$service\"}[1m]))[$interval:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总接口数",
   "type": "stat",
   "description": "总接口数",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group(http_server_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\"}) by(path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "【$service】HTTP总请求",
   "type": "stat",
   "description": "记录的是服务启动以来的数据",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_duration_ms_count{namespace=\"${namespace}\", service=\"${service}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 接口请求耗时分布【$interval】(ms)",
   "type": "bargauge",
   "description": "请求耗时分布，统计服务所有请求各个区间【$interval】的耗时分布，单位ms",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service, le)(\n    increase(\n        http_server_requests_duration_ms_bucket{namespace=~\"${namespace}\", service=~\"${service}\"}[$interval]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "接口请求延时热力图",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_server_requests_duration_ms_bucket{namespace=\"${namespace}\", service=\"${service}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "${service} 所有 接口 汇总QPS",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\" }[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": " 接口请求量($interval)",
   "type": "timeseries",
   "description": "接口请求量，$interval的维度进行统计",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_duration_ms_count{namespace=\"${namespace}\", service=\"${service}\"}[$interval])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "各接口 QPS （by Pod）",
   "type": "timeseries",
   "description": "${service} 各个 path 的QPS",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\" }[5m])) by (path,pod)",
     "legendFormat": "{{path}} | {{pod}}"
    }
   ]
  },
  {
   "title": "各接口 QPS（by path）",
   "type": "timeseries",
   "description": "${service} 各个 server method 的QPS",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\" }[5m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平均耗时（ms）",
   "type": "timeseries",
   "description": "接口请求的平均耗时",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_duration_ms_sum{namespace=\"${namespace}\",service=\"${service}\"}[5m])) \n/ \nsum(rate(http_server_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\"}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "接口维度-$path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": " 接口请求耗时分布【$interval】(ms)",
   "type": "bargauge",
   "description": "请求耗时分布，统计服务所有请求各个区间【$interval】的耗时分布，单位ms",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service, le) (increase(http_server_requests_duration_ms_bucket{namespace=\"${namespace}\", service=\"${service}\", path=\"${path}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平均耗时（ms）",
   "type": "timeseries",
   "description": "接口 $path 平均耗时",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_duration_ms_sum{namespace=\"${namespace}\",service=\"${service}\",path=\"${path}\"}[5m])) \n/ \nsum(rate(http_server_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\",path=\"${path}\"}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "RPC-Client【$service】如有则显示", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "RPC Client 请求耗时分布【$interval】(ms)",
   "type": "bargauge",
   "description": "client 请求耗时分布，统计服务所有请求各个区间【$interval】的耗时分布，单位ms",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service, le) (increase(rpc_client_requests_duration_ms_bucket{namespace=\"${namespace}\", service=\"${service}\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Client接口请求延时热力图",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "sum by (le) (increase(rpc_client_requests_duration_ms_bucket{namespace=\"${namespace}\", service=\"${service}\"}[$interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Client QPS",
   "type": "timeseries",
   "description": "${service} 所有 method 汇总QPS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\" }[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "RPC Client 各接口 QPS （by method）",
   "type": "timeseries",
   "description": "${service} 各个 client method 的QPS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\" }[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Client 各接口 QPS （by Pod）",
   "type": "timeseries",
   "description": "${service} 各个 client method 的QPS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\" }[5m])) by (method,pod)",
     "legendFormat": "{{method}} | {{pod}}"
    }
   ]
  },
  {
   "title": "RPC Client 接口请求量($interval)",
   "type": "timeseries",
   "description": "接口请求量，$interval的维度进行统计",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sum(increase(rpc_client_requests_duration_ms_count{namespace=\"${namespace}\", service=\"${service}\"}[$interval])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Client 平均耗时（ms）",
   "type": "timeseries",
   "description": "RPC 客户端请求的平均耗时",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_requests_duration_ms_sum{namespace=\"${namespace}\",service=\"${service}\"}[5m])) \n/ \nsum(rate(rpc_client_requests_duration_ms_count{namespace=\"${namespace}\",service=\"${service}\"}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "RPC Client P95 延迟（ms）",
   "type": "timeseries",
   "description": "95分位延迟",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum (rate(rpc_client_requests_duration_ms_bucket{namespace=\"${namespace}\",service=\"${service}\"}[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}