{
 "title": "API-Biz",
 "tags": [
  "API",
  "Go"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(biz_sub_duration_ms_bucket,namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(biz_sub_duration_ms_count{namespace=\"$namespace\"},service)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(biz_sub_duration_ms_count{service=~\"$service\", namespace=~\"$namespace\"},type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "业务请求耗时分布",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(biz_sub_duration_ms_bucket{namespace=~\"$namespace\",service=~\"$service\",type=~\"$type\", le!=\"+Inf\"}[$__range])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "业务请求耗时分布(万分比)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(biz_sub_duration_ms_bucket{namespace=~\"$namespace\",service=~\"$service\",type=~\"$type\", le!=\"+Inf\"}[$__range])) by (le)\n/\nignoring(le) group_left\nsum(increase(biz_sub_duration_ms_count{namespace=~\"$namespace\",service=~\"$service\",type=~\"$type\"}[$__range])) * 10000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "业务模块QPS",
   "type": "timeseries",
   "description": "基于服务维度统计各服务总QPS",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(biz_sub_duration_ms_count{namespace=~\"$namespace\",service=~\"$service\",type=~\"$type\"}[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "业务请求耗时热力图",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (increase(biz_sub_duration_ms_bucket{namespace=~\"$namespace\",service=~\"$service\",type=~\"$type\"}[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "业务模块请求耗时 【Type维度】 P90",
   "type": "timeseries",
   "description": "基于服务+Type维度计算各type请求耗时，计算耗时的 90 分位数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (service, type, le) (rate(biz_sub_duration_ms_bucket{namespace=~\"$namespace\",service=~\"$service\",type=~\"$type\"}[5m])))",
     "legendFormat": "{{service}} | {{type}}"
    }
   ]
  },
  {
   "title": "业务模块QPS 【Type维度】",
   "type": "timeseries",
   "description": "基于服务维度统计各服务总QPS",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service, type) (rate(biz_sub_duration_ms_count{namespace=~\"$namespace\",service=~\"$service\",type=~\"$type\"}[5m]))",
     "legendFormat": "{{service}} | {{type}}"
    }
   ]
  },
  {
   "title": "业务模块请求平均耗时【Type维度】",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (service, type)(rate(biz_sub_duration_ms_sum{namespace=~\"$namespace\",service=~\"$service\",type=~\"$type\"}[5m])) / sum by(service,type) (rate(biz_sub_duration_ms_count{namespace=~\"$namespace\",service=~\"$service\",type=~\"$type\"}[5m]))",
     "legendFormat": "{{service}} | {{type}}"
    }
   ]
  },
  {
   "title": "业务模块请求耗时 【Type维度】 P95",
   "type": "timeseries",
   "description": "基于服务+Type维度计算各type请求耗时，计算耗时的 95 分位数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (service, type, le) (rate(biz_sub_duration_ms_bucket{namespace=~\"$namespace\",service=~\"$service\",type=~\"$type\"}[5m])))",
     "legendFormat": "{{service}} | {{type}}"
    }
   ]
  }
 ]
}