{
 "title": "API-SLS",
 "tags": [
  "API",
  "SLS"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "API-Dev,API-Test,API-Prev,API-Prod"
   },
   { "name": "prom_ds", "query": "prometheus" },
   { "name": "ext_request_log_ds", "query": "elasticsearch" },
   { "name": "bill_ds", "query": "elasticsearch" },
   { "name": "wallet_center_ds", "query": "elasticsearch" },
   { "name": "sls_api_log_ds", "query": "aliyun-log-service-datasource" },
   { "name": "operator", "label": "Operator", "query": { "query": "" } }
  ]
 },
 "panels": [
  { "title": "QPS统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Order QPS",
   "type": "timeseries",
   "description": "wallet-center下所有订单相关 RPC 汇总QPS(包括bet/award)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_requests_duration_ms_count{namespace=\"api-center\",service=\"wallet-center\",method=~\"/game\\\\.GameService/Bet|/game\\\\.GameService/Award\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bill QPS",
   "type": "timeseries",
   "description": "基于日志 LogStore （bill）的数据计算其QPS值",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "运营商请求模块【$operator】 -- 可关联Operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "运营商API异常请求",
   "type": "timeseries",
   "description": "请求运营商接口，返回状态非200数目统计，按照 operator_id 进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "operator",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "not status_code: 200 and operator: $operator",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "运营商API异常分布【状态码维度】",
   "type": "piechart",
   "description": "请求运营商接口，非200状态的分布情况，基于状态码进行百分比占比计算",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "status_code",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "not status_code : 200 and operator : $operator",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "运营商API异常分布【运营商维度】",
   "type": "piechart",
   "description": "请求运营商接口，非200状态的分布情况，基于运营商ID进行百分比占比计算",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "operator",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "not status_code : 200 and operator : $operator",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "运营商API异常分布【状态/方法】维度",
   "type": "table",
   "description": "请求运营商接口，返回状态非200数目统计，按照 状态码 和请求方法进行分组",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "status_code",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "api_method",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "status",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "url",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "not status_code :200 and operator: $operator",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "运营商API请求耗时分布",
   "type": "table",
   "description": "请求运营商API接口，耗时分布请求",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "currentPage": 1,
     "logsPerPage": 100,
     "logstore": "ext_request_log",
     "query": "(operator : $operator) and cost : *\n| SELECT\n    FLOOR(cost / 1000) * 1000 AS cost_level,\n    COUNT(*) AS cnt,\n    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 4) AS percentage\nGROUP BY cost_level\nORDER BY cost_level",
     "totalLogs": 100,
     "type": "all"
    }
   ]
  },
  {
   "title": "请求运营商耗时大于1秒",
   "type": "timeseries",
   "description": "按照运营商维度，统计请求运营商耗时大于1秒的请求。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "operator",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "cost:[1000 TO *] and operator: $operator",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "请求运营商耗时大于1秒，按运营商和接口维度",
   "type": "timeseries",
   "description": "按照运营商维度，统计请求运营商耗时大于1秒的请求。并基于运营商和接口维度进行分组。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "operator",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "api_method",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "cost:[1000 TO *] and operator: $operator",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "请求运营商API RT分位数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cost",
       "id": "1",
       "settings": {
        "percents": [
         "50",
         "90",
         "95",
         "99"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "operator: $operator",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "wallet-center",
   "type": "timeseries",
   "description": "统计wallet-center的日志错误数，以及slow_call数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "alias": "错误数(已排除slow_call)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "level: error not gozero_level: slow",
     "timeField": "@timestamp"
    },
    {
     "alias": "slow_call",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "gozero_level: slow",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "交易相关", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "交易去重",
   "type": "table",
   "description": "基于 LogStore (ext_request_log) 进行查询统计",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "currentPage": 1,
     "logsPerPage": 100,
     "logstore": "ext_request_log",
     "query": "api_method=cancelBet| SELECT 1, sum(is_success) AS success, sum(1 - is_success) AS fail FROM (\nSELECT\n\"request_body.orderId\",\nCASE\nWHEN bool_or(status_code = 200 AND \"response_body.code\" = 0) THEN 1\nELSE 0\nEND as is_success\nFROM log\nGROUP BY \"request_body.orderId\"\n)",
     "totalLogs": 100,
     "type": "all",
     "xcol": "t"
    },
    {
     "currentPage": 1,
     "logsPerPage": 100,
     "logstore": "ext_request_log",
     "query": "api_method=award\n| SELECT 1,\nsum(is_recovered) AS award_success,\nsum(1 - is_recovered) AS award_fail\nFROM (\nSELECT\n\"request_body.orderId\",\n-- 如果该 ID 在所有记录中存在一条 200/0 的记录，则视为重试成功\nMAX(CASE WHEN status_code = 200 AND \"response_body.code\" = 0 THEN 1 ELSE 0 END) as is_recovered\nFROM log\nWHERE \"request_body.orderId\" IN (\n-- 【核心步】：先锁定所有发生过失败的订单 ID\nSELECT \"request_body.orderId\"\nFROM log\nWHERE status_code != 200 OR \"response_body.code\" != 0\n)\nGROUP BY \"request_body.orderId\"\n)",
     "totalLogs": 100,
     "type": "all",
     "xcol": "t"
    }
   ]
  },
  {
   "title": "交易统计 -- 可关联Operator",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "确定失败bet",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:bet and status_code:200 and not response_body.code:0 and operator: $operator",
     "timeField": "@timestamp"
    },
    {
     "alias": "不确定bet状态数量",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:bet and not status_code: 200 and operator: $operator",
     "timeField": "@timestamp"
    },
    {
     "alias": "余额不足bet数量",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:bet and status_code:200 and response_body.code:8205 and operator: $operator",
     "timeField": "@timestamp"
    },
    {
     "alias": "撤销bet次数",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:cancelBet and operator: $operator",
     "timeField": "@timestamp"
    },
    {
     "alias": "撤销成功次数",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:cancelBet and status_code:200 and response_body.code:0 and operator: $operator",
     "timeField": "@timestamp"
    },
    {
     "alias": "撤销失败次数",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:cancelBet and (not status_code:200 or not response_body.code:0) and operator: $operator",
     "timeField": "@timestamp"
    },
    {
     "alias": "award 失败次数",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:award and (not status_code:200 or not response_body.code:0) and operator: $operator",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "交易统计趋势 -- 可关联Operator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "alias": "确定失败bet",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:bet and status_code:200 and not response_body.code:0 and operator: $operator",
     "timeField": "@timestamp"
    },
    {
     "alias": "不确定bet状态数量",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:bet and not status_code: 200 and operator: $operator",
     "timeField": "@timestamp"
    },
    {
     "alias": "余额不足bet数量",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:bet and status_code:200 and response_body.code:8205 and operator: $operator",
     "timeField": "@timestamp"
    },
    {
     "alias": "撤销bet次数",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:cancelBet and operator: $operator",
     "timeField": "@timestamp"
    },
    {
     "alias": "撤销成功次数",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:cancelBet and status_code:200 and response_body.code:0 and operator: $operator",
     "timeField": "@timestamp"
    },
    {
     "alias": "撤销失败次数",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:cancelBet and (not status_code:200 or not response_body.code:0) and operator: $operator",
     "timeField": "@timestamp"
    },
    {
     "alias": "award 失败次数",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "api_method:award and (not status_code:200 or not response_body.code:0) and operator: $operator",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}