{
 "title": "API-Game-分析",
 "description": "游戏内存使用分析",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_statefulset_created,namespace)"
    }
   },
   {
    "name": "game",
    "label": "Game",
    "query": {
     "query": "query_result(group(label_replace(kube_statefulset_created{namespace=\"${namespace}\",statefulset=~\"\\\\d+(-a$|-b$)\"}, \"game\", \"$1\", \"statefulset\", \"(\\\\d+).*\")) by(game))"
    }
   },
   {
    "name": "statefulset",
    "label": "StatefulSet",
    "query": {
     "query": "query_result(sum by (created_by_name) ( kube_pod_info{created_by_kind=\"StatefulSet\", created_by_name=~\"${game}-(a|b)$\"}     and on(pod, namespace) kube_pod_status_phase{phase=\"Running\"})  > 0)"
    }
   }
  ]
 },
 "panels": [
  { "title": "游戏【$game】分析", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "部署时间",
   "type": "stat",
   "description": "记录的是游戏部署的时间",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_created{statefulset=~\"${game}-a$|${game}-b$\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "启动时间",
   "type": "stat",
   "description": "记录的当前资源的最后启动时间",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (namespace, created_by_name) (\n  kube_pod_start_time\n  * on(namespace, pod) group_left(created_by_name)\n  kube_pod_info{created_by_kind=\"StatefulSet\", created_by_name=~\"${game}-a$|${game}-b$\", namespace=\"${namespace}\"}\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "游戏当前运行版本（蓝 / 绿）",
   "type": "stat",
   "description": "当前游戏实例实际在跑的是蓝绿中的哪一套（A / B）",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n    sum by (created_by_name) (\n        kube_pod_info{namespace=\"${namespace}\", created_by_kind=\"StatefulSet\", created_by_name=~\"${game}-(a|b)$\"}\n        and on(pod, namespace)\n        kube_pod_status_phase{namespace=\"${namespace}\", phase=\"Running\"}\n    ) > 0\n) by (created_by_name)",
     "legendFormat": "{{created_by_name}}"
    }
   ]
  },
  {
   "title": "游戏蓝绿资源并存状态",
   "type": "stat",
   "description": "检查游戏是否同时存在蓝（A）与绿（B）资源，若同时存在则表示蓝绿发布状态异常。",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    sum by (created_by_name) (\n        kube_pod_info{namespace=\"${namespace}\", created_by_kind=\"StatefulSet\", created_by_name=~\"${game}-(a|b)$\"}\n        and on(pod, namespace)\n        kube_pod_status_phase{phase=\"Running\"}\n    ) > 0\n) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "游戏副本数",
   "type": "stat",
   "description": "统计处于Ready状态副本数",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas_ready{statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "$statefulset"
    }
   ]
  },
  {
   "title": "文件描述符汇总",
   "type": "stat",
   "description": "基于文件描述符进行统计，游戏维度汇总",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (process_open_fds{namespace=~\"${namespace}\", pod=~\"${game}.*\"})",
     "legendFormat": "$statefulset"
    }
   ]
  },
  {
   "title": "CPU使用总量（Core）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  group (kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}) by (pod)\n  * on(pod) \n  max by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",image!=\"\",container!=\"POD\"}[5m]))\n)",
     "legendFormat": "$statefulset"
    }
   ]
  },
  {
   "title": "内存使用总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  group (kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}) by (pod)\n  * on(pod) \n  max by (pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\",image!=\"\", container!=\"POD\"})\n)",
     "legendFormat": "$statefulset"
    }
   ]
  },
  {
   "title": "单个游戏资源请求与使用总量",
   "type": "table",
   "description": "统计某个游戏下 所有 Pod 的资源请求量与实际使用量的总和，用于评估该游戏整体资源占用情况。",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(\n  group (kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}) by (pod)\n  * on(pod) \n  max by (pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\",image!=\"\", container!=\"POD\"})\n)"
    },
    {
     "expr": "sum(\n  group (kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}) by (pod)\n  * on(pod) \n  max by (pod) (kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"})\n)"
    },
    {
     "expr": "sum(\n  group (kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}) by (pod)\n  * on(pod) \n  max by (pod) (kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"})\n)"
    },
    {
     "expr": "sum(\n  group (kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}) by (pod)\n  * on(pod) \n  max by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",image!=\"\",container!=\"POD\"}[5m]))\n)"
    },
    {
     "expr": "sum(\n  group (kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}) by (pod)\n  * on(pod) \n  max by (pod) (kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"})\n)"
    },
    {
     "expr": "sum(\n  group (kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}) by (pod)\n  * on(pod) \n  max by (pod) (kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"})\n)"
    },
    {
     "expr": "sum(\n  # 获取StatefulSet的CPU使用率总和\n  sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",image!=\"\",container!=\"POD\"}[5m]))\n  * on(pod) group_left(created_by_name)\n  kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}\n)\n/\n# 获取该StatefulSet的CPU请求总和\nsum(\n  kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$namespace\"}\n  * on(pod) group_left(created_by_name)\n  kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}\n)",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(\n  # 获取StatefulSet的CPU使用率总和\n  sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",image!=\"\",container!=\"POD\"}[5m]))\n  * on(pod) group_left(created_by_name)\n  kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}\n)\n/\n# 获取该StatefulSet的CPU限制总和\nsum(\n  kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\"}\n  * on(pod) group_left(created_by_name)\n  kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}\n)",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "# 获取该StatefulSet的内存使用总量\nsum (\n    sum by(pod) (\n    container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\",image!=\"\",container!=\"POD\"} \n    * on(pod) group_left(created_by_name)\n    kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}\n    )\n)\n/\nsum(\n  group (kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}) by (pod)\n  * on(pod) \n  max by (pod) (kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"})\n)"
    },
    {
     "expr": "# 获取该StatefulSet的内存使用总量\nsum (\n    sum by(pod) (\n    container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\",image!=\"\",container!=\"POD\"} \n    * on(pod) group_left(created_by_name)\n    kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}\n    )\n)\n/\nsum(\n  group (kube_pod_info{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", created_by_name=\"$statefulset\"}) by (pod)\n  * on(pod) \n  max by (pod) (kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"})\n)"
    }
   ]
  },
  {
   "title": "文件描述符使用情况",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$namespace\",pod=~\"$game.*\"}",
     "legendFormat": "{{pod}} - open_fds"
    }
   ]
  },
  {
   "title": "文件描述符使用汇总",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(process_open_fds{namespace=\"$namespace\",pod=~\"$game.*\"})",
     "legendFormat": "users"
    }
   ]
  },
  {
   "title": "游戏Pod详情",
   "type": "table",
   "description": "当前游戏所运行的Pod详情",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",created_by_name=\"$statefulset\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\"} * (kube_pod_status_phase{namespace=\"$namespace\"} > 0)) by (uid, phase)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$namespace\"} * (kube_pod_status_ready{namespace=\"$namespace\"} > 0)) by (uid, condition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max(kube_pod_created{namespace=\"$namespace\"}) by (uid)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by (uid, container)) by (uid)"
    },
    {
     "expr": "max(kube_pod_container_info{namespace=\"$namespace\"}) by (uid, container, image)"
    }
   ]
  },
  {
   "title": "副本数变化趋势",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Desired"
    },
    {
     "expr": "max(kube_statefulset_status_replicas{statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Current"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_ready{statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Ready"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_available{statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_updated{statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Updated"
    }
   ]
  },
  {
   "title": "内存限制",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",container!=\"\"}) by (pod))",
     "legendFormat": "合计"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",container!=\"\"}) by (pod))",
     "legendFormat": "单Pod"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "timeseries",
   "description": "展示该游戏对应工作负载的每个 Pod 内存使用量。",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() max by(container, pod, image) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", container!=\"POD\"}))by (container, pod, image)",
     "legendFormat": "Usage: {{pod}}"
    },
    {
     "expr": "max(avg(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() max by(container, pod, image) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\"}))by (container, pod))by(container)",
     "legendFormat": "Request: {{container}}"
    },
    {
     "expr": "max(avg(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() max by(container, pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\"}))by (container, pod))by(container)",
     "legendFormat": "Limit: {{container}}"
    }
   ]
  },
  {
   "title": "内存请求",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "合计"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "单Pod"
    }
   ]
  },
  {
   "title": "CPU限制",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "合计"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "单Pod"
    }
   ]
  },
  {
   "title": "CPU使用量（Core）",
   "type": "timeseries",
   "description": "展示该游戏对应工作负载每个 Pod 的 CPU 使用量。",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[5m])) by (pod, container,image)",
     "legendFormat": "Usage: {{pod}}"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n    * on(pod) group_right() max(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\"}) by (pod, container,image) \n) by (container)",
     "legendFormat": "Limit: {{container}}"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() max(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$namespace\"}) by (pod, container,image)) by (container)",
     "legendFormat": "Request: {{container}}"
    }
   ]
  },
  {
   "title": "CPU请求",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "合计"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "单Pod"
    }
   ]
  },
  {
   "title": "内存使用率(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() max by(container, pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", container!=\"POD\"})/max by(container, pod) (kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}/{{container}}(Limit)"
    },
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() max by(container, pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", container!=\"POD\"})/max by(container, pod) (kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}/{{container}}(Request)"
    }
   ]
  },
  {
   "title": "CPU使用率(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[5m])) by (pod, container) / max by(container, pod) (kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}/{{container}}(Limit)"
    },
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\", container!=\"POD\"}[5m])) by (pod, container) / max by(container, pod) (kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}/{{container}}(Request)"
    }
   ]
  },
  {
   "title": "网络入流量",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod))"
    }
   ]
  },
  {
   "title": "网络出流量",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod每秒网络带宽",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() max(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}-In"
    },
    {
     "expr": "-sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$statefulset\"}) by (pod)\n* on(pod) group_right() max(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}-Out"
    }
   ]
  }
 ]
}