{
 "title": "Go Processes（GC）",
 "description": "go程序运行时资源使用，以及gc相关指标。",
 "tags": [
  "API",
  "Go"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(go_goroutines{namespace=\"$namespace\"},service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(go_goroutines{namespace=\"$namespace\", service=\"$service\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Go 版本",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Go 运行时线程数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{namespace=\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go GC 触发阈值（GOGC）",
   "type": "stat",
   "description": "当前 Go 程序的 GOGC 参数，控制堆内存增长到一定比例后触发 GC。值越大，GC 越少但内存占用越高；值越小，GC 越频繁但内存占用更低。",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_gc_gogc_percent{namespace=\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "最近一次 GC 时间",
   "type": "stat",
   "description": "Go Runtime 最近一次垃圾回收（GC）完成的时间点",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_last_gc_time_seconds{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"} * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC 平均耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}[5m]) / rate(go_gc_duration_seconds_count{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "平均每分钟 GC 次数",
   "type": "timeseries",
   "description": "过去 5 分钟内，平均每分钟发生的 GC 次数，计算每秒的平均增长率，然后乘以 60 得到每分钟的次数",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}[5m]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "下一次 GC 触发点",
   "type": "timeseries",
   "description": "go_memstats_next_gc_bytes (下一次 GC 触发点)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - next_gc"
    }
   ]
  },
  {
   "title": "堆对象分配速率（次/s）",
   "type": "timeseries",
   "description": "累计分配的堆对象（Heap Objects）。\ngo_memstats_mallocs_total",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "irate(go_memstats_mallocs_total{namespace=\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go GC 耗时（暂停时间）",
   "type": "timeseries",
   "description": "Go 垃圾回收（GC）每次执行所消耗时间的分布情况，单位为秒。",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: {{quantile}}"
    }
   ]
  },
  {
   "title": "Goroutines 数量",
   "type": "timeseries",
   "description": "当前 Go 程序中活跃的 Goroutine 数量，用于观察并发规模及是否存在 Goroutine 泄漏风险。",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "运行时系统内存",
   "type": "timeseries",
   "description": "Go 运行时向操作系统申请的内存总量",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go 堆内存使用概览",
   "type": "timeseries",
   "description": "该面板展示 Go 程序堆内存的整体使用情况，包括已分配、正在使用、空闲、已释放以及 Go 运行时为堆申请的系统内存，用于分析内存使用效率和 GC 行为。\n•   heap_alloc_bytes：当前已分配并仍被使用的堆内存（业务对象实际占用）\n•   heap_inuse_bytes：正在使用的堆内存空间（包含已分配对象及内部碎片）\n•   heap_idle_bytes：已向系统申请但当前未使用的堆内存\n•   heap_released_bytes：已归还给操作系统的空闲堆内存\n•   heap_sys_bytes：Go 运行时为堆管理向系统申请的总内存",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - heap_alloc"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - heap_idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - heap_inuse"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - heap_sys"
    },
    {
     "expr": "go_memstats_heap_released_bytes{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - heap_released"
    }
   ]
  },
  {
   "title": "Go 栈内存使用概览",
   "type": "timeseries",
   "description": "Go 程序中 Goroutine 栈内存的使用情况，其中包含实际使用的栈内存以及 Go Runtime 为栈预留的内存，用于分析协程规模和栈内存开销。",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - inuse"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - sys"
    }
   ]
  },
  {
   "title": "堆内存分配速率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "进程 CPU 使用时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}[5m]) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "文件描述符使用情况",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - open_fds"
    }
   ]
  }
 ]
}