{
 "title": "Kubernetes Cluster",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "节点总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pod总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deployment总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_deployment_created)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "StatefulSet总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_statefulset_created)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DaemonSet总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_daemonset_created)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DaemonSet总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_cronjob_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "节点CPU平均请求占用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by(node) (kube_pod_container_resource_requests{resource=\"cpu\"}) / sum by (node) (kube_node_status_capacity{resource=\"cpu\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点内存平均请求占用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by(node) (kube_pod_container_resource_requests{resource=\"memory\"}) / sum by (node) (kube_node_status_capacity{resource=\"memory\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "命名空间概览",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count(kube_pod_info{}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{}) by (namespace)"
    },
    {
     "expr": "count(kube_pod_container_info{}) by (namespace)"
    },
    {
     "expr": "count(kube_configmap_info{}) by (namespace)"
    },
    {
     "expr": "count(kube_secret_info{}) by (namespace)"
    },
    {
     "expr": "count(kube_persistentvolumeclaim_info{}) by (namespace)"
    },
    {
     "expr": "count(kube_deployment_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_job_info{}) by (namespace)"
    },
    {
     "expr": "count(kube_cronjob_info{}) by (namespace)"
    },
    {
     "expr": "count(kube_pod_status_ready{condition=\"false\"}==1) by (namespace) - (count(kube_pod_status_phase{phase=\"Succeeded\"}==1) by (namespace) or vector(0)) or count(kube_pod_status_ready{condition=\"false\"}==1) by (namespace)"
    }
   ]
  },
  {
   "title": "节点池概览",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(kube_node_labels) by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_allocatable{resource=\"memory\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity{resource=\"memory\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_allocatable{resource=\"cpu\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity{resource=\"cpu\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_spec_unschedulable==1)by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info{})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum((max(kube_pod_status_phase{phase=\"Running\"}) by (pod) > 0) * on (pod) group_right() kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests{resource=\"memory\"})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info * on (pod) group_left() (sum(kube_pod_container_resource_requests{resource=\"memory\"}) by(pod) * on (pod) group_right() (max(kube_pod_status_phase{phase=\"Running\"}) by (pod) > 0)))by (node))by(label_alibabacloud_com_nodepool_id) / sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity{resource=\"memory\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum((max(kube_pod_status_phase{phase=\"Running\"}) by (pod) > 0) * on (pod) group_right() kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests{resource=\"cpu\"})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id) / sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity{resource=\"cpu\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum((max(kube_pod_status_phase{phase=\"Running\"}) by (pod) > 0) * on (pod) group_right() kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests{resource=\"cpu\"})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() count((max(kube_pod_status_phase{phase!=\"Running\"}) by (pod,namespace,phase) > 0) * on (pod,namespace) group_right() group(kube_pod_info) by (pod,namespace,node)) by (node)) by (label_alibabacloud_com_nodepool_id)"
    }
   ]
  },
  {
   "title": "节点内存使用率（Top10）",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(label_replace(topk(10, 1-(node_memory_MemAvailable_bytes{} / node_memory_MemTotal_bytes{})), \"node_ip\", \"$1\", \"instance\", \"(.*):(.*)\")) by(node_ip)"
    }
   ]
  },
  {
   "title": "节点CPU使用率（Top10）",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total[1m])) by (instance),\"node_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(node_ip))"
    }
   ]
  },
  {
   "title": "节点磁盘使用率（Top10）",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(1-node_filesystem_free_bytes{mountpoint=\"/\"}/node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"},\"node_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(node_ip))"
    }
   ]
  },
  {
   "title": "网络入站流量（Top10）",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(max(irate(node_network_receive_bytes_total{}[1m])) by (instance),\"node_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(node_ip))"
    }
   ]
  },
  {
   "title": "网络入站流量（Top10）",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(max(irate(node_network_transmit_bytes_total{}[1m])) by (instance),\"node_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(node_ip))"
    }
   ]
  },
  {
   "title": "Sockets（Top10）",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 19 },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(max(node_sockstat_TCP_alloc) by (instance),\"node_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(node_ip))"
    }
   ]
  },
  {
   "title": "容器内存使用量（Top10）",
   "type": "timeseries",
   "description": "容器内存使用量前10，按容器名聚合",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(container_memory_working_set_bytes{container!=\"\", container!=\"POD\"}) by (container))",
     "legendFormat": "[Container]:{{container}}"
    }
   ]
  },
  {
   "title": "容器内存使用率 / Limit（Top10）",
   "type": "timeseries",
   "description": "容器内存使用率，基于limit进行计算",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, (max(container_memory_working_set_bytes{container!=\"\", container!=\"POD\"}) by (pod, container, namespace) / max(kube_pod_container_resource_limits{resource=\"memory\", container!=\"\"}) by (pod, container, namespace)) <= 100 or on() vector(0))",
     "legendFormat": "[Container]:{{pod}}:{{container}}"
    }
   ]
  },
  {
   "title": "容器CPU使用量（Top10）",
   "type": "timeseries",
   "description": "容器CPU使用量前10，按容器名聚合",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\",namespace=\"api-center\"}[2m])) by (container,pod))",
     "legendFormat": "[Container]:{{container}}"
    }
   ]
  },
  {
   "title": "容器CPU使用率 / Limit（Top10）",
   "type": "timeseries",
   "description": "容器CPU使用率，基于limit进行计算",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, (sum(rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\"}[5m])) by (pod) / sum( kube_pod_container_resource_limits{resource=\"cpu\",container!=\"POD\"} ) by (pod)) )",
     "legendFormat": "[Container]:{{pod}}:{{container}}"
    }
   ]
  },
  {
   "title": "容器网络流量使用情况（Top10）",
   "type": "timeseries",
   "description": "容器网络流量贷款使用情况",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_network_receive_bytes_total{image!=\"\"}[2m])) by (pod))",
     "legendFormat": "Receive:[Pod]:{{pod}}"
    },
    {
     "expr": "-topk(10, sum(irate(container_network_transmit_bytes_total{image!=\"\"}[2m])) by (pod))",
     "legendFormat": "Transmit:[Pod]:{{pod}}"
    }
   ]
  }
 ]
}