{
 "title": "Kubernetes Node",
 "tags": [
  "Kubernetes",
  "Node",
  "scene:container",
  "env:type:ManagedKubernetes",
  "dashboard:name:k8s-node-overview"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cluster", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info{system_uuid!=\"\"}, internal_ip)"
    }
   },
   {
    "name": "nodeInstance",
    "query": {
     "query": "label_values(kube_node_info{system_uuid!=\"\",internal_ip=\"$node\"}, node)"
    }
   },
   { "name": "port", "query": ":.*" }
  ]
 },
 "panels": [
  {
   "title": "System Run Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\".*($node|$nodeInstance)$port\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=~\".*($node|$nodeInstance)$port\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pod Request Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\"$nodeInstance\"})by(node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod List",
   "type": "table",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "group (kube_pod_info{host_ip=\"$node\"})by(created_by_kind, created_by_name,host_network,pod_ip,pod,priority_class,namespace)",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    },
    {
     "expr": " min(kube_pod_info{host_ip=\"$node\"})by(pod) * on(pod) group_right() max(kube_pod_status_phase{}==1) by (pod, phase) "
    },
    {
     "expr": " min(kube_pod_info{host_ip=\"$node\"})by(pod) * on(pod) group_right() sum(container_memory_working_set_bytes{container !=\"\",container!=\"POD\"}) by (pod) "
    },
    {
     "expr": " min(kube_pod_info{host_ip=\"$node\"})by(pod) * on(pod) group_right() sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) by (pod)"
    },
    {
     "expr": "min(kube_pod_info{host_ip=\"$node\"})by(pod) * on(pod) group_right() max(time()-kube_pod_start_time) by (pod) "
    },
    {
     "expr": "min(kube_pod_info{host_ip=\"$node\"})by(pod) * on(pod) max(kube_pod_status_ready{condition=\"true\"}) by (pod) or on() vector(0)"
    },
    {
     "expr": "min(kube_pod_info{host_ip=\"$node\"})by(pod) * on(pod) group_right() max(rate(container_network_receive_bytes_total{image!=\"\"}[5m])) by (pod) or on() vector(0)"
    },
    {
     "expr": "min(kube_pod_info{host_ip=\"$node\"})by(pod) * on(pod) group_right() max(rate(container_network_transmit_bytes_total{image!=\"\"}[5m])) by (pod) or on() vector(0)"
    },
    {
     "expr": "min(kube_pod_info{host_ip=\"$node\"})by(pod) * on(pod) group_right() max(rate(container_fs_reads_bytes_total{container!=\"POD\", container!=\"\"}[5m])) by (pod) or on() vector(0)"
    },
    {
     "expr": "min(kube_pod_info{host_ip=\"$node\"})by(pod) * on(pod) group_right() max(rate(container_fs_writes_bytes_total{container!=\"POD\", container!=\"\"}[5m])) by (pod) or on() vector(0)"
    },
    {
     "expr": "min(kube_pod_info{host_ip=\"$node\"}) by (pod) * on(pod) group_right sum by (pod) (container_fs_usage_bytes)"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\".*($node|$nodeInstance)$port\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Pod Request CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\"$nodeInstance\"})by(node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Pool ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "kube_node_labels{node=~\"$nodeInstance\"}",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{node=~\"$nodeInstance\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "kube_node_status_capacity_pods{node=~\"$nodeInstance\"}",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "group(kube_node_info{node=~\"$nodeInstance\"})by(node, pod_cidr, kubelet_version,kernel_version,container_runtime_version)",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  { "title": "Node Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Boot Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time()-node_boot_time_seconds" }
   ]
  },
  {
   "title": "CPU Usage Percent (5m)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\".*($node|$nodeInstance)$port\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU IOwait（5m）",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\".*($node|$nodeInstance)$port\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((1 - (node_memory_MemAvailable_bytes{instance=~\".*($node|$nodeInstance)$port\"} / (node_memory_MemTotal_bytes{instance=~\".*($node|$nodeInstance)$port\"})))* 100)"
    }
   ]
  },
  {
   "title": "File Descriptor Usage Percent",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_filefd_allocated{instance=~\".*($node|$nodeInstance)$port\"})/max(node_filefd_maximum{instance=~\".*($node|$nodeInstance)$port\"})"
    }
   ]
  },
  {
   "title": "Root Partition Usage Percent",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - ((node_filesystem_free_bytes{instance=~\".*($node|$nodeInstance)$port\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes {instance=~\".*($node|$nodeInstance)$port\",mountpoint=\"/\"}))"
    }
   ]
  },
  {
   "title": "Network Socket Alloc",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_sockstat_TCP_alloc{instance=~\".*($node|$nodeInstance)$port\"})"
    }
   ]
  },
  {
   "title": "Average System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\".*($node|$nodeInstance)$port\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\".*($node|$nodeInstance)$port\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\".*($node|$nodeInstance)$port\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Disk File System",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(node_filesystem_size_bytes{instance=~'.*($node|$nodeInstance)$port',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    },
    {
     "expr": "(max(node_filesystem_size_bytes{instance=~'.*($node|$nodeInstance)$port',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint) - max(node_filesystem_free_bytes{instance=~'.*($node|$nodeInstance)$port',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint))/max(node_filesystem_size_bytes{instance=~'.*($node|$nodeInstance)$port',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    },
    {
     "expr": "max(node_filesystem_size_bytes{instance=~'.*($node|$nodeInstance)$port',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)-max(node_filesystem_free_bytes{instance=~'.*($node|$nodeInstance)$port',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    },
    {
     "expr": "max(node_filesystem_avail_bytes{instance=~'.*($node|$nodeInstance)$port',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "这里CPU使用率、磁盘每秒IO操作耗时使用率 % 此图每根线的含义：\n\nSystem，是CPU系统部分CPU时间片占总CPU时间片的百分比，也就是CPU系统部分的CPU使用率%\nUser，是CPU User部分CPU时间片占总CPU时间片的百分比，也就是CPU User部分的CPU使用率%\nIowait，是CPU Iowait部分CPU时间片占总CPU时间片的百分比，也就是CPU Iowait部分的CPU使用率%\n\n{{device}}_每秒I/O操作% 这根线是每个设备（如vda），IO操作的时间占总IO时间的占比，也就是此设备的IO使用率 %\nnode_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的毫秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\".*($node|$nodeInstance)$port\",mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\".*($node|$nodeInstance)$port\",mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\".*($node|$nodeInstance)$port\",mode=\"iowait\"}[1m]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\".*($node|$nodeInstance)$port\"}[1m])",
     "legendFormat": "{{device}}_I/O operations per second%"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\".*($node|$nodeInstance)$port\"}",
     "legendFormat": "Total memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\".*($node|$nodeInstance)$port\"} - node_memory_MemAvailable_bytes{instance=~\".*($node|$nodeInstance)$port\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\".*($node|$nodeInstance)$port\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Read / Write Rate (IOPs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\".*($node|$nodeInstance)$port\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\".*($node|$nodeInstance)$port\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "Disk Read / Write ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\".*($node|$nodeInstance)$port\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\".*($node|$nodeInstance)$port\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "Disk IO Read / Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\".*($node|$nodeInstance)$port\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\".*($node|$nodeInstance)$port\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "Disk IO Read / Write Latency (Time/IO)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\".*($node|$nodeInstance)$port\"}[1m])/irate(node_disk_reads_completed_total{instance=~\".*($node|$nodeInstance)$port\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\".*($node|$nodeInstance)$port\"}[1m])/irate(node_disk_writes_completed_total{instance=~\".*($node|$nodeInstance)$port\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "Disk File System Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(max(node_filesystem_size_bytes{instance=~'.*($node|$nodeInstance)$port',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint) - max(node_filesystem_free_bytes{instance=~'.*($node|$nodeInstance)$port',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint))/max(node_filesystem_size_bytes{instance=~'.*($node|$nodeInstance)$port',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    }
   ]
  },
  {
   "title": "Disk File System Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(node_filesystem_size_bytes{instance=~'.*($node|$nodeInstance)$port',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint) - max(node_filesystem_free_bytes{instance=~'.*($node|$nodeInstance)$port',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    }
   ]
  },
  {
   "title": "Disk File System Available (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(node_filesystem_avail_bytes{instance=~'.*($node|$nodeInstance)$port',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    }
   ]
  },
  {
   "title": "PVC Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "node_volume_capacity_bytes_total{node=~\".*$node.*\"} * on(pvc) group_left(pv)\nlabel_replace( \n    label_replace(\n        group by (volumename, persistentvolumeclaim) (kube_persistentvolumeclaim_info),\n        \"pv\", \"$1\", \"volumename\", \"(.*)\"\n    ),\n    \"pvc\", \"$1\", \"persistentvolumeclaim\", \"(.*)\"\n)",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    },
    {
     "expr": "node_volume_capacity_bytes_used{node=~\".*$node.*\"}"
    },
    {
     "expr": "label_replace(\n    label_replace(kube_persistentvolumeclaim_info, \"pv\", \"$1\", \"volumename\", \"(.*)\"),\n    \"pvc\", \"$1\", \"persistentvolumeclaim\", \"(.*)\"\n)\n* on(pv) group_left(type, Source)\nlabel_replace(\n    group by (pv, bucket_name, backend_storage) (node_volume_capacity_bytes_available_counter{node=~\".*$node.*\"}),\n    \"type\", \"$1\", \"backend_storage\", \"(.*)\"\n)"
    }
   ]
  },
  {
   "title": "PVC Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "irate(node_volume_read_bytes_total{node=~\".*$node.*\"}[5m])",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Read {{pvc}}",
     "method": "GET"
    },
    {
     "expr": "irate(node_volume_write_bytes_total{node=~\".*$node.*\"}[5m])",
     "legendFormat": "Write {{pvc}}"
    }
   ]
  },
  {
   "title": "Network Traffic Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'.*($node|$nodeInstance)$port',device!~'tap.*'}[5m])",
     "legendFormat": "{{device}}_in"
    }
   ]
  },
  {
   "title": "Network Traffic Transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'.*($node|$nodeInstance)$port',device!~'tap.*'}[5m])",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "TCP Connection",
   "type": "timeseries",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'.*($node|$nodeInstance)$port'}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'.*($node|$nodeInstance)$port'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'.*($node|$nodeInstance)$port'}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'.*($node|$nodeInstance)$port'}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'.*($node|$nodeInstance)$port'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'.*($node|$nodeInstance)$port'}",
     "legendFormat": "TCP_inuse"
    }
   ]
  },
  {
   "title": "Scheduling Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Container Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(max(container_memory_working_set_bytes{container !=\"\",container!=\"POD\",node=~\".*($node|$nodeInstance).*\"}) by (pod,namespace,container))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(max(kube_pod_container_resource_requests{resource=\"memory\",container !=\"\",container!=\"POD\",node=~\".*($node|$nodeInstance).*\"}) by (container,pod,namespace))",
       "legendFormat": "Request"
      },
      {
       "expr": "sum(max(kube_pod_container_resource_limits{resource=\"memory\",container !=\"\",container!=\"POD\",node=~\".*($node|$nodeInstance).*\"}) by (container,pod,namespace))",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Total Container Memory Percent (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(max(container_memory_working_set_bytes{container !=\"\",container!=\"POD\",node=~\".*($node|$nodeInstance).*\"}) by (pod,namespace,container)) / sum(max(kube_node_status_capacity{resource=\"memory\",node=~\".*($node|$nodeInstance).*\"}) by (node)) or on() vector(0)",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(max(kube_pod_container_resource_requests{resource=\"memory\", container !=\"\",container!=\"POD\",node=~\".*($node|$nodeInstance).*\"}) by (container,pod,namespace)) / sum(max(kube_node_status_capacity{resource=\"memory\", node=~\".*($node|$nodeInstance).*\"}) by (node)) or on() vector(0)",
       "legendFormat": "Request"
      },
      {
       "expr": "sum(max(kube_pod_container_resource_limits{resource=\"memory\",container !=\"\",container!=\"POD\",node=~\".*($node|$nodeInstance).*\"}) by (container,pod,namespace)) / sum(max(kube_node_status_capacity{resource=\"memory\", node=~\".*($node|$nodeInstance).*\"}) by (node)) or on() vector(0)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Total Container CPU Cores",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(max(irate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",node=~\".*($node|$nodeInstance).*\"}[1m])) by (pod,container,namespace)) or on() vector(0)",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(max(kube_pod_container_resource_requests{resource=\"cpu\",container!=\"\",container!=\"POD\",node=~\".*($node|$nodeInstance).*\"}) by (container,pod,namespace)) or on() vector(0)",
       "legendFormat": "Request"
      },
      {
       "expr": "sum(max(kube_pod_container_resource_limits{resource=\"cpu\",container!=\"\",container!=\"POD\",node=~\".*($node|$nodeInstance).*\"}) by (container,pod,namespace)) or on() vector(0)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Total Container CPU Percent (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(max(irate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",node=~\".*($node|$nodeInstance).*\"}[1m])) by (pod,container,namespace)) / sum(max(kube_node_status_capacity{resource=\"cpu\",node=~\".*($node|$nodeInstance).*\"}) by (node)) or on() vector(0)",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(max(kube_pod_container_resource_requests{resource=\"cpu\",container!=\"\",container!=\"POD\",node=~\".*($node|$nodeInstance).*\"}) by (container,pod,namespace)) / sum(max(kube_node_status_capacity{resource=\"cpu\",node=~\".*($node|$nodeInstance).*\"}) by (node)) or on() vector(0)",
       "legendFormat": "Request"
      },
      {
       "expr": "sum(max(kube_pod_container_resource_limits{resource=\"cpu\",container!=\"\",container!=\"POD\",node=~\".*($node|$nodeInstance).*\"}) by (container,pod,namespace)) / sum(max(kube_node_status_capacity{resource=\"cpu\",node=~\".*($node|$nodeInstance).*\"}) by (node)) or on() vector(0)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Container CPU Usage By Cores",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(max(kube_pod_info{node=~\"(.*${node}:.*)|(.*${node})\"}) by (namespace,pod) * on(namespace,pod) group_right() max(kube_pod_container_info) by (namespace,pod,container)) * on(container,namespace,pod) group_left() (max(irate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[1m])) by (pod,container,namespace)) or on() vector(0)",
       "legendFormat": "{{pod}}/{{container}}"
      }
     ]
    },
    {
     "title": "Container CPU Usage (%)",
     "type": "timeseries",
     "description": "容器 CPU 使用量相对于限制值的百分比。 ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(max(kube_pod_info{node=~\"(.*${node}:.*)|(.*${node})\"}) by (namespace,pod) * on(namespace,pod) group_right() max(kube_pod_container_info) by (namespace,pod,container)) * on(container,namespace,pod) group_left() (max(irate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[1m])) by (container,namespace,pod) / max(kube_pod_container_resource_limits{resource=\"cpu\",container!=\"\",container!=\"POD\"}) by (container,namespace,pod)) or on() vector(0)",
       "legendFormat": "{{pod}}/{{container}}"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(max(kube_pod_info{node=~\"(.*${node}:.*)|(.*${node})\"}) by (namespace,pod) * on(namespace,pod) group_right() max(kube_pod_container_info) by (namespace,pod,container)) * on(container,namespace,pod) group_left() (max(container_memory_working_set_bytes{container !=\"\",container!=\"POD\"}) by (pod,namespace,container))",
       "legendFormat": "{{pod}}/{{container}}(WSS)"
      }
     ]
    },
    {
     "title": "Container Memory Usage /Limit (%)",
     "type": "timeseries",
     "description": "提供了 RSS, Usage, WorkingSet 三种维度的内存使用量相对于限制量的比例。通常以 WorkingSet 作为最关键的参考。 ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(max(kube_pod_info{node=~\"(.*${node}:.*)|(.*${node})\"}) by (namespace,pod) * on(namespace,pod) group_right() max(kube_pod_container_info) by (namespace,pod,container)) * on(container,namespace,pod) group_left() ((max(container_memory_working_set_bytes{container !=\"\",container!=\"POD\"}) by (pod,namespace,container)/ max(kube_pod_container_resource_limits{resource=\"memory\",container !=\"\",container!=\"POD\"}) by (pod,namespace, container) * 100) <= 100) or on() vector(0)",
       "legendFormat": "{{pod}}/{{container}}(WSS/Limit)"
      }
     ]
    },
    {
     "title": "Container Network Input (Excluding the use of HostWork)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(max(kube_pod_info{node=~\"(.*${node}:.*)|(.*${node})\"}) by (namespace,pod) * on(namespace,pod) group_left() (max (rate (container_network_receive_bytes_total{image!=\"\"}[1m])) by(pod,namespace))) unless on(pod, namespace) (max by (pod, namespace) (kube_pod_info{host_network=\"true\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Container Network Output (Excluding the use of HostWork)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(max(kube_pod_info{node=~\"(.*${node}:.*)|(.*${node})\"}) by (namespace,pod) * on(namespace,pod) group_left() max (rate (container_network_transmit_bytes_total{image!=\"\"}[1m])) by (pod,namespace))  unless on(pod, namespace) (max by (pod, namespace) (kube_pod_info{host_network=\"true\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}