{
 "title": "Kubernetes Pod",
 "tags": [
  "Kubernetes",
  "Workload",
  "Pod",
  "scene:container",
  "addon:name:cs-default",
  "dashboard:name:k8s-pod"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_created, namespace)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, node)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\",node=~\"${node}.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_namespace_created{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_pod_created{pod=~\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_status_ready{namespace=\"$namespace\", pod=~\"$pod\", condition=\"true\"}) or on() vector(0)",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "title": "Phase",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$pod\"}==1) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "group by (image, container,pod) (kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (container,pod)(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Restarts"
    },
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Memory Request"
    },
    {
     "expr": "max by (container,pod)(kube_pod_container_status_running{namespace=\"$namespace\", pod=~\"$pod\"})"
    },
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "Node Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{pod=~\"$pod\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restart Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum (increase(kube_pod_container_status_restarts_total{pod=~\"$pod\",namespace=\"$namespace\"}[1h])))",
     "legendFormat": "Last 1 Hour"
    },
    {
     "expr": "sum(max(kube_pod_container_status_restarts_total{pod=~\"$pod\",namespace=\"$namespace\"})by (pod))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"$pod\",namespace=~\"$namespace\",node=~\"$node\"}) or vector(0)",
     "legendFormat": "CPU (cores)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",pod=~\"$pod\",namespace=~\"$namespace\",node=~\"$node\"}) or vector(0)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"$pod\",namespace=~\"$namespace\",node=~\"$node\"}) or vector(0)",
     "legendFormat": "CPU (cores)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$pod\",namespace=~\"$namespace\",node=~\"$node\"}) or vector(0)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Warning Events",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "ceil(increase(eventer_events_error_total{namespace=\"$namespace\", name=\"$pod\", kind=\"Pod\"}[1m]))>0 or ceil(increase(eventer_events_warning_total{namespace=\"$namespace\", name=\"$pod\", kind=\"Pod\"}[1m]))>0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "CPU Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "description": "容器 CPU 使用量相对于限制值的百分比。 ",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{pod=~\"$pod\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}[1m])) by (container,namespace,pod) / max(kube_pod_container_resource_requests{resource=\"cpu\", pod=~\"$pod\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (container,namespace,pod) or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage By Cores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{pod=~\"$pod\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}[1m])) by (pod,container,namespace)or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Throttled Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max (rate (container_cpu_cfs_throttled_seconds_total{image!=\"\", container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"}[1m])) by (container,pod) / max (rate (container_cpu_cfs_periods_total{image!=\"\", container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"}[1m])) by (container,pod) or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  { "title": "Memory Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (pod,namespace,container)",
     "legendFormat": "{{pod}}/{{container}}(WSS)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (pod,namespace,container)",
     "legendFormat": "{{pod}}/{{container}}(Usage)"
    }
   ]
  },
  {
   "title": "Memory Usage（RSS）",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_rss{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (pod,namespace,container) or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}(RSS)"
    }
   ]
  },
  {
   "title": "Usage WSS/Limit (%)",
   "type": "timeseries",
   "description": "提供了 RSS, Usage, WorkingSet 三种维度的内存使用量相对于限制量的比例。通常以 WorkingSet 作为最关键的参考。 ",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(max(container_memory_working_set_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (pod,namespace,container)/ max(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (pod,namespace, container) * 100) <= 100 or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}(WSS/Limit)"
    }
   ]
  },
  {
   "title": "Usage/Limit (%)",
   "type": "timeseries",
   "description": "提供了 RSS, Usage, WorkingSet 三种维度的内存使用量相对于限制量的比例。通常以 WorkingSet 作为最关键的参考。 ",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((max(container_memory_usage_bytes{container!=\"\",container!=\"POD\",namespace=~\"$namespace\",pod=~\"$pod\",node=~\"$node\"})  by(pod,container,namespace) / max(kube_pod_container_resource_limits{resource=\"memory\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\",pod=~\"$pod\",node=~\"$node\"}) by(pod,container,namespace)) * 100) <= 100 or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}(Usage/Limit)"
    }
   ]
  },
  {
   "title": "Usage RSS/Limit (%)",
   "type": "timeseries",
   "description": "提供了 RSS, Usage, WorkingSet 三种维度的内存使用量相对于限制量的比例。通常以 WorkingSet 作为最关键的参考。 ",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(max(container_memory_rss{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (pod,namespace,container)/ sum(kube_pod_container_resource_limits{resource=\"memory\", pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (pod,namespace, container) * 100) <= 100 or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}(RSS/Limit)"
    }
   ]
  },
  {
   "title": "Memory Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_cache{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\",node=~\"$node\"}) by (pod,namespace,container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Network & File System & Process Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Network Input",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max (rate (container_network_receive_bytes_total{image!=\"\",namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\"}[1m])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Output",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max (rate (container_network_transmit_bytes_total{image!=\"\",namespace=~\"$namespace\", pod=~\"$pod\",node=~\"$node\"}[1m]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}