{
 "title": "Kubernetes Namespace",
 "tags": [
  "Kubernetes",
  "Overview",
  "scene:container",
  "env:type:ManagedKubernetes",
  "dashboard:name:k8s-namespace"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cluster", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_namespace_status_phase{namespace=\"$Namespace\", phase=\"Active\"})",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "High Memory Usage(>85%)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(container, pod) (container_memory_working_set_bytes{namespace=\"$Namespace\", container!=\"\", image!=\"\", container!=\"POD\"})/sum by(container, pod) (kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$Namespace\"})>0.85",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "High CPU Usage(>85% ||  >1 Core)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container, pod) (rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"$Namespace\"}[2m]))/sum by(container, pod) (kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$Namespace\"})> 0.85",
     "legendFormat": "{{pod}}/{{container}}(Usage/Limit)"
    },
    {
     "expr": "sum by (container, pod) (rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"$Namespace\"}[1m])) > 0.9",
     "legendFormat": "{{pod}}/{{container}}(Cores)"
    }
   ]
  },
  {
   "title": "High Bandwidth Usage(>1MiB/s)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{image!=\"\", namespace=~\"$Namespace\"}[2m])) by (pod) > 1024*1024",
     "legendFormat": "{{pod}}-Receive"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{image!=\"\", namespace=~\"$Namespace\"}[2m])) by (pod) > 1024*1024",
     "legendFormat": "{{pod}}-Transmit"
    }
   ]
  },
  {
   "title": "CPU Usage In Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\"}[2m])) or on() vector(0)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\"}[2m]))/sum(kube_pod_container_resource_requests{namespace=~\"$Namespace\", unit=\"core\", resource=\"cpu\"}) or on() vector(0)",
     "legendFormat": "Usage/Request(%)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\"}[2m]))/sum(kube_pod_container_resource_limits{namespace=~\"$Namespace\", unit=\"core\", resource=\"cpu\"}) or on() vector(0)",
     "legendFormat": "Usage/Limit(%)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$Namespace\", unit=\"core\", resource=\"cpu\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$Namespace\", unit=\"core\", resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "kube_resourcequota{namespace=~\"$Namespace\", resource=\"limits.cpu\", type=\"hard\"} ",
     "legendFormat": "Quota"
    },
    {
     "expr": "sum(sum(kube_node_status_capacity{resource=\"cpu\"}) by (node) + sum(kube_node_spec_unschedulable==0) by(node)) or on() vector(0)",
     "legendFormat": "Cluster  Available"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-max(kube_namespace_created{namespace=\"$Namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Insight",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{condition=\"false\", namespace=\"$Namespace\"}==1) by(namespace) - (count(kube_pod_status_phase{phase=\"Succeeded\", namespace=\"$Namespace\"}==1) by(namespace) or vector(0)) or count(kube_pod_status_ready{condition=\"false\", namespace=\"$Namespace\"}==1) by(namespace)",
     "legendFormat": "NotReady"
    },
    {
     "expr": "count(kube_pod_status_unschedulable{namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "UnSchedulable"
    }
   ]
  },
  {
   "title": "Workload Insight",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(kube_deployment_status_replicas_ready{namespace=\"$Namespace\"}) by (deployment)<sum(kube_deployment_spec_replicas{namespace=\"$Namespace\"}) by (deployment)) or on() vector(0)",
     "legendFormat": "NotReady Deployment"
    },
    {
     "expr": "count(sum(kube_statefulset_status_replicas_ready{namespace=\"$Namespace\"})by(statefulset)<sum(kube_statefulset_replicas{namespace=\"$Namespace\"})by (statefulset)) or on() vector(0)",
     "legendFormat": "NotReady Statefulset"
    },
    {
     "expr": "count(kube_daemonset_status_number_unavailable{namespace=\"$Namespace\"}>0) or on() vector(0)",
     "legendFormat": "NotReady Daemonset"
    },
    {
     "expr": "count(kube_job_status_failed{namespace=\"$Namespace\"} == 1)",
     "legendFormat": "Failed Job"
    }
   ]
  },
  {
   "title": "Memory Usage In Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$Namespace\"})/sum(kube_pod_container_resource_requests{namespace=~\"$Namespace\", unit=\"byte\", resource=\"memory\"}) or on() vector(0)",
     "legendFormat": "Usage/Request(%)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$Namespace\"})/sum(kube_pod_container_resource_limits{namespace=~\"$Namespace\", unit=\"byte\", resource=\"memory\"}) or on() vector(0)",
     "legendFormat": "Usage/Limit(%)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$Namespace\", unit=\"byte\", resource=\"memory\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$Namespace\", unit=\"byte\", resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "kube_resourcequota{namespace=~\"$Namespace\", resource=\"limits.memory\", type=\"hard\"}",
     "legendFormat": "Quota"
    },
    {
     "expr": "sum(sum(kube_node_status_capacity{resource=\"memory\"}) by (node) + sum(kube_node_spec_unschedulable==0) by(node)) or on() vector(0)",
     "legendFormat": "Cluster  Available"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_resourcequota_created{namespace=\"$Namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Unbound PVC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\", namespace=\"$Namespace\"}==1) or on() vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error Events(1h)",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum(increase(eventer_events_error_total{namespace='$Namespace'}[1h])) by (kind, name, reason)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warning Event Trends",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum(increase(eventer_events_warning_total{namespace='$Namespace'}[1h]))by(kind, reason, name))>0",
     "legendFormat": "{{kind}}/{{name}}/{{reason}}"
    }
   ]
  },
  {
   "title": "Pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(kube_resourcequota{namespace=\"$Namespace\", resource=\"pods\", type=\"hard\"})",
     "legendFormat": "Quota"
    },
    {
     "expr": "count(kube_pod_container_info{namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "ConfigMap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_configmap_info{namespace=\"$Namespace\"})",
     "legendFormat": "Created"
    },
    {
     "expr": "max(kube_resourcequota{namespace=\"$Namespace\", resource=\"configmaps\", type=\"hard\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "LoadBalancer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_service_spec_type{type=\"LoadBalancer\", namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(kube_resourcequota{namespace=\"$Namespace\", resource=\"services.loadbalancers\", type=\"hard\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Secret",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_secret_info{namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(kube_resourcequota{namespace=\"$Namespace\", resource=\"secrets\", type=\"hard\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_service_info{namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(kube_resourcequota{namespace=\"$Namespace\", resource=\"services\", type=\"hard\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_ingress_info{namespace=\"$Namespace\"})or on() vector(0)",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "PersistentVolumeClaim",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(kube_resourcequota{namespace=\"$Namespace\", resource=\"persistentvolumeclaims\", type=\"hard\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "PVC Storage Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(sum by (persistentvolumeclaim) (kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$Namespace\"}) and group by (persistentvolumeclaim) (kube_persistentvolumeclaim_status_phase{phase=\"Bound\", namespace=\"$Namespace\"} == 1)) or on() vector(0)",
     "legendFormat": "Bounded"
    }
   ]
  },
  {
   "title": "Deployment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_created{namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "StatefulSet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_statefulset_created{namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "DaemonSet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_daemonset_created{namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "Cron Job",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_cronjob_created{namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "count(kube_cronjob_status_active{namespace=\"$Namespace\"}==1) or on() vector(0)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Job",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_job_info{namespace=\"$Namespace\"})or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "count(kube_job_status_active{namespace=\"$Namespace\"}==1)or on() vector(0)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Hot Images",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 16 },
   "targets": [
    {
     "expr": "sort_desc(sum by(image) (kube_pod_container_info{namespace=\"$Namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "group by (image, container, container_id, pod) (kube_pod_container_info{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{namespace=\"$Namespace\"}) * on(container,pod) group_left() max by (container,pod)(kube_pod_container_status_running{namespace=\"$Namespace\"})"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{namespace=\"$Namespace\"}) * on(container,pod) group_left() max by (container,pod)(kube_pod_container_status_restarts_total{namespace=\"$Namespace\"})",
     "legendFormat": "Restarts"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{namespace=\"$Namespace\"}) * on(container,pod) group_left() max(irate(container_cpu_usage_seconds_total{namespace=\"$Namespace\",container!=\"\",container!=\"POD\"}[1m])) by (pod,container)"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{namespace=\"$Namespace\"}) * on(container,pod) group_left() (max(irate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",namespace=\"$Namespace\"}[1m])) by (container,pod) / (max(kube_pod_container_resource_limits{resource=\"cpu\",container!=\"\",container!=\"POD\",namespace=~\"$Namespace\"} > 0) by (container,pod)))"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{namespace=\"$Namespace\"}) * on(container,pod) group_left() sum by (container,pod)(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$Namespace\"})",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{namespace=\"$Namespace\"}) * on(container,pod) group_left() (max(irate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",namespace=\"$Namespace\"}[1m])) by (container,pod) / (max by (container,pod)(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$Namespace\"})))"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{namespace=\"$Namespace\"}) * on(container,pod) group_left() sum by (container,pod)(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$Namespace\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{namespace=\"$Namespace\"}) * on(container,pod) group_left() max(container_memory_working_set_bytes{container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (pod,container)"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{namespace=\"$Namespace\"}) * on(container,pod) group_left() (max(container_memory_working_set_bytes{container!=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (pod,container) / max(kube_pod_container_resource_limits{resource=\"memory\",container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (pod, container) < 1)"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{namespace=\"$Namespace\"}) * on(container,pod) group_left() sum by (container,pod)(kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$Namespace\"})",
     "legendFormat": "Memory Request"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{namespace=\"$Namespace\"}) * on(container,pod) group_left() (max(container_memory_working_set_bytes{container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (pod,container) / max by (container,pod)(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$Namespace\"}))"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{namespace=\"$Namespace\"}) * on(container,pod) group_left() sum by (container,pod)(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$Namespace\"})",
     "legendFormat": "Memory Limit"
    }
   ]
  }
 ]
}