{
 "title": "Kubernetes StatefulSet",
 "description": "Kubernetes StatefulSet Overview",
 "tags": [
  "Kubernetes",
  "StatefulSet",
  "scene:container",
  "env:type:ManagedKubernetes",
  "dashboard:name:k8s-statefulset"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_statefulset_created, namespace)"
    }
   },
   {
    "name": "name",
    "label": "StatefulSet",
    "query": {
     "query": "label_values(kube_statefulset_created{namespace=\"$namespace\"}, statefulset)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_namespace_created{namespace=\"$namespace\"})by(namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "description": "Time since StatefulSet created.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_statefulset_created{namespace=\"$namespace\",statefulset=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_metadata_generation{namespace=\"$namespace\", statefulset=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\",statefulset=\"$name\"}/kube_statefulset_replicas{namespace=\"$namespace\",statefulset=\"$name\"}",
     "legendFormat": "$name"
    }
   ]
  },
  {
   "title": "Replicas(Pods)",
   "type": "stat",
   "description": "Number of desired replicas.",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{statefulset=\"$name\",namespace=\"$namespace\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max(kube_statefulset_status_replicas_ready{statefulset=\"$name\",namespace=\"$namespace\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "max(kube_statefulset_status_replicas_ready{statefulset=\"$name\",namespace=\"$namespace\"}) / max(kube_statefulset_replicas{statefulset=\"$name\",namespace=\"$namespace\"})",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Replica Trend",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{statefulset=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Desired"
    },
    {
     "expr": "max(kube_statefulset_status_replicas{statefulset=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Current"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_ready{statefulset=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Ready"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_available{statefulset=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_updated{statefulset=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Updated"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",created_by_name=\"$name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\"} * (kube_pod_status_phase{namespace=\"$namespace\"} > 0)) by (uid, phase)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$namespace\"} * (kube_pod_status_ready{namespace=\"$namespace\"} > 0)) by (uid, condition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max(kube_pod_created{namespace=\"$namespace\"}) by (uid)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by (uid, container)) by (uid)"
    }
   ]
  },
  {
   "title": "Focus Error Events",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum(increase(eventer_events_error_total{namespace='$namespace', kind=\"Statefulset\", name=\"$name\"}[1h])) by (kind, name, reason)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",container!=\"\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",container!=\"\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "展示该工作负载的每个 Pod 内存使用量。",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max by(container, pod, image) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", container!=\"POD\"}))by (container, pod, image)",
     "legendFormat": "Usage: {{pod}}/{{container}}  Image: {{image}}"
    },
    {
     "expr": "max(avg(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max by(container, pod, image) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\"}))by (container, pod))by(container)",
     "legendFormat": "Request: {{container}}"
    },
    {
     "expr": "max(avg(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max by(container, pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\"}))by (container, pod))by(container)",
     "legendFormat": "Limit: {{container}}"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "展示该工作负载每个 Pod 的 CPU 使用量。",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[5m])) by (pod, container,image)",
     "legendFormat": "{{pod}}/{{container}} Image:{{image}}"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n    * on(pod) group_right() max(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\"}) by (pod, container,image) \n) by (container)",
     "legendFormat": "Limit: {{container}}"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$namespace\"}) by (pod, container,image)) by (container)",
     "legendFormat": "Request: {{container}}"
    }
   ]
  },
  {
   "title": "CPU Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "Memory Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max by(container, pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", container!=\"POD\"})/max by(container, pod) (kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}/{{container}}(Limit)"
    },
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max by(container, pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", container!=\"POD\"})/max by(container, pod) (kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}/{{container}}(Request)"
    }
   ]
  },
  {
   "title": "CPU Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\"}[5m])) by (pod, container) / max by(container, pod) (kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}/{{container}}(Limit)"
    },
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\"}[5m])) by (pod, container) / max by(container, pod) (kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}/{{container}}(Request)"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod))"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}-In"
    },
    {
     "expr": "-sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}-Out"
    }
   ]
  }
 ]
}