{
 "title": "Kubernetes DaemonSet",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "Kubernetes",
  "DaemonSet",
  "scene:container",
  "env:type:ManagedKubernetes",
  "dashboard:name:k8s-daemonset"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_daemonset_created, namespace)"
    }
   },
   {
    "name": "daemonset",
    "label": "daemonset",
    "query": {
     "query": "label_values(kube_daemonset_created{namespace=~\"$namespace\"},daemonset)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~'$namespace',pod=~\"$daemonset.*\"} ,pod)"
    }
   },
   {
    "name": "Pod_ip",
    "label": "Pod Ip",
    "query": {
     "query": "label_values(kube_pod_info{pod=~'$Pod'} ,pod_ip)"
    }
   },
   {
    "name": "phase",
    "query": {
     "query": "query_result(kube_pod_status_phase{pod=~'$Pod'} >= 1)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{pod=~'$Pod'} ,container)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace='$namespace', pod_name='$Pod'} ,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "statefulset", "type": "text", "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 }, "options": { "content": "\n# $container\n\n\n" } },
  {
   "title": "Pod Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum(container_memory_working_set_bytes{pod=~\"$Pod\",namespace=\"$namespace\"}) by(pod))"
    }
   ]
  },
  {
   "title": "spec_replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(kube_daemonset_status_desired_number_scheduled{daemonset=\"$daemonset\"})"
    }
   ]
  },
  {
   "title": "Pod Mem Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod memory limit",
   "type": "stat",
   "description": "没有配额的情况下默认值是0",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$Pod\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Secs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "restarts_total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (  (kube_pod_container_status_restarts_total{ pod=~\"$Pod\",namespace=\"$namespace\"} ))"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "max (kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$Pod\",namespace=\"$namespace\"})>0",
     "legendFormat": "limit"
    },
    {
     "expr": "max (kube_pod_container_resource_requests{resource=\"memory\",pod=~\"$Pod\",namespace=\"$namespace\"})>0",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "max (kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"$Pod\",namespace=\"$namespace\"})>0",
     "legendFormat": "limit"
    },
    {
     "expr": "max (kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"$Pod\",namespace=\"$namespace\"})>0",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "Received {{pod_name}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "Sent {{pod_name}}"
    }
   ]
  }
 ]
}