{
 "title": "Kubernetes Deployment",
 "description": "Kubernetes Deployment Overview",
 "tags": [
  "Workload",
  "Kubernetes",
  "scene:container",
  "env:type:ManagedKubernetes",
  "dashboard:name:k8s-deploy"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_created, namespace)"
    }
   },
   {
    "name": "name",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_created{namespace=\"$namespace\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_namespace_created{namespace=\"$namespace\"})by(namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "description": "Time since deployment created.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_deployment_created{namespace=\"$namespace\",deployment=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas(Pods)",
   "type": "stat",
   "description": "工作副本数量统计",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$name\",namespace=\"$namespace\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max(kube_deployment_status_replicas_ready{deployment=\"$name\",namespace=\"$namespace\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "max(kube_deployment_status_replicas_ready{deployment=\"$name\",namespace=\"$namespace\"}) / max(kube_deployment_spec_replicas{deployment=\"$name\",namespace=\"$namespace\"})",
     "legendFormat": "Ready Percent"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=\"$name\"}/kube_deployment_spec_replicas{namespace=\"$namespace\",deployment=\"$name\"}",
     "legendFormat": "$name"
    }
   ]
  },
  {
   "title": "Replica  Trend",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Desired"
    },
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Current"
    },
    {
     "expr": "min(kube_deployment_status_replicas_ready{deployment=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Ready"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Updated"
    },
    {
     "expr": "min(kube_deployment_status_replicas_unavailable{deployment=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\"} * (kube_pod_status_phase{namespace=\"$namespace\"} > 0)) by (uid, phase)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$namespace\"} * (kube_pod_status_ready{namespace=\"$namespace\"} > 0)) by (uid, condition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max(kube_pod_created{namespace=\"$namespace\"}) by (uid)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by (uid, container)) by (uid)"
    }
   ]
  },
  {
   "title": "Error Events",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum(increase(eventer_events_error_total{namespace='$namespace', kind=\"Deployment\", name=\"$name\"}[1h])) by (kind, name, reason)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "CPU Info",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[1m])) by (pod, container)",
     "legendFormat": "Usage: {{pod}}/{{container}}"
    },
    {
     "expr": "max(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$namespace\",container!=\"\",container!=\"POD\"}) by (pod, container))by(container)",
     "legendFormat": "Request: {{container}}"
    },
    {
     "expr": "max(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\",container!=\"\",container!=\"POD\"}) by (pod, container))by(container)",
     "legendFormat": "Limit: {{container}}"
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "CPU Usage/Limit (%)",
   "type": "timeseries",
   "description": "CPU 使用量除以 CPU 限制量。若没有数据需要检查相应容器是否进行了 CPU Limit 的配置。",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[1m])) by (pod, container) / max by(container, pod) (kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}/{{container}}(Limit)"
    }
   ]
  },
  {
   "title": "CPU Usage/Request (%)",
   "type": "timeseries",
   "description": "CPU 使用量除以 CPU 请求量。若没有数据需要检查相应容器是否进行了 CPU Request 的配置。",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[1m])) by (pod, container) / max by(container, pod) (kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}/{{container}}(Request)"
    }
   ]
  },
  { "title": "Memory Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Memory Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "Memory Info",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max by(container, pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", container!=\"POD\"})\n",
     "legendFormat": "Usage: {{pod}}/{{container}}"
    },
    {
     "expr": "max(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max by(container, pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\"}))by(container)",
     "legendFormat": "Limit: {{container}}"
    },
    {
     "expr": "max(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max by(container, pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\"}))by(container)",
     "legendFormat": "Request: {{container}}"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",container!=\"\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",container!=\"\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "Memory Usage/Limit (%)",
   "type": "timeseries",
   "description": "内存使用量除以内存限制量。若没有数据需要检查相应容器是否进行了 Memory Limit 的配置。",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max by(container, pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", container!=\"POD\"})/max by(container, pod) (kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"})\n",
     "legendFormat": "{{pod}}/{{container}}(Limit)"
    }
   ]
  },
  {
   "title": "Memory Usage/Request (%)",
   "type": "timeseries",
   "description": "内存使用量除以内存请求量。若没有数据需要检查相应容器是否进行了 Memory Request 的配置。",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max by(container, pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", container!=\"POD\"})/max by(container, pod) (kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"})\n",
     "legendFormat": "{{pod}}/{{container}}(Request)"
    }
   ]
  },
  { "title": "Network & File System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Network In",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod))"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Input",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}-In"
    }
   ]
  },
  {
   "title": "Network Output",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}-Out"
    }
   ]
  },
  {
   "title": "File System Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(rate(container_fs_writes_bytes_total{namespace=\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) by (pod,container,device)",
     "legendFormat": "{{pod}}(Write)"
    }
   ]
  },
  {
   "title": "File System Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(rate(container_fs_reads_bytes_total{namespace=\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) by (pod,container,device)",
     "legendFormat": "{{pod}}(Write)"
    }
   ]
  }
 ]
}