{
 "title": "Kubernetes HPA",
 "description": "Kubernetes (k8s) Horizontal Pod Autoscaler (HPA)",
 "tags": [
  "Kubernetes",
  "HPA",
  "dashboard:name:k8s-hpa"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_info,namespace)"
    }
   },
   {
    "name": "hpa",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_info{namespace=~\"$namespace\"},horizontalpodautoscaler)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$hpa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hpa" },
  {
   "title": "Target metrics ($hpa)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{namespace=~\"$namespace\",horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "target -  ({{metric_target_type}}: {{metric_name}})"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{namespace=~\"$namespace\", horizontalpodautoscaler=~\"$hpa\"}\nand on(metric_name, metric_target_type)\nkube_horizontalpodautoscaler_spec_target_metric{namespace=~\"$namespace\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "current -  ({{metric_target_type}}: {{metric_name}})"
    }
   ]
  },
  {
   "title": "Replicas（$hpa）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=~\"$namespace\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "min"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{namespace=~\"$namespace\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "desired"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$namespace\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Max Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=~\"$namespace\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  },
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$namespace\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  },
  {
   "title": "Min Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=~\"$namespace\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  }
 ]
}