{
 "title": "Node Pool",
 "tags": [
  "Kubernetes",
  "Node",
  "Node Pool",
  "scene:container",
  "env:type:ManagedKubernetes",
  "dashboard:name:k8s-node-pool"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cluster", "query": "prometheus" },
   {
    "name": "nodepool",
    "label": "Node Pool",
    "query": {
     "query": "label_values(kube_node_labels,label_alibabacloud_com_nodepool_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "count(group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip))",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Total",
     "method": "GET"
    },
    {
     "expr": "count(group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() kube_node_spec_unschedulable==1)",
     "legendFormat": "UnSchedulable"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "sum(\n  sum by (host_ip) (label_replace(node_memory_MemTotal_bytes, \"host_ip\", \"$1\", \"instance\", \"([0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+):.*\"))\n  * on (host_ip) \n  label_replace(group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"}) by(node), \"host_ip\", \"$1\", \"node\",\".*[^0-9]((\\\\d{1,3}\\\\.){3}\\\\d{1,3})$\")\n)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Total",
     "method": "GET"
    },
    {
     "expr": "sum(\n  sum by (host_ip) (\n    label_replace(\n      node_memory_MemTotal_bytes,\n      \"host_ip\", \"$1\",\n      \"instance\", \"([0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+):.*\"\n    )\n  )\n  * on (host_ip)\n  label_replace(\n    (\n      group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"npf823a185d9f24e51a075c48a5ace2211\"}) by (node)\n      * on (node)\n      kube_node_spec_unschedulable == 1\n    ),\n    \"host_ip\", \"$1\",\n    \"node\", \".*[^0-9]((\\\\d{1,3}\\\\.){3}\\\\d{1,3})$\"\n  )\n)",
     "legendFormat": "UnSchedulable"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "sum(\n    count by (host_ip) (label_replace(node_cpu_seconds_total{mode=\"system\"}, \"host_ip\", \"$1\", \"instance\", \"([0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+):.*\")) \n    * on (host_ip) \n    label_replace(group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"}) by(node), \"host_ip\", \"$1\", \"node\",\".*[^0-9]((\\\\d{1,3}\\\\.){3}\\\\d{1,3})$\")\n)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Total",
     "method": "GET"
    },
    {
     "expr": "sum(\n    count by (host_ip) (label_replace(node_cpu_seconds_total{mode=\"system\"}, \"host_ip\", \"$1\", \"instance\", \"([0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+):.*\")) \n    * on (host_ip) \n    label_replace(\n        (\n        group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"npf823a185d9f24e51a075c48a5ace2211\"}) by (node)\n            * on (node)\n            kube_node_spec_unschedulable == 1\n        ),\n        \"host_ip\", \"$1\",\n        \"node\", \".*[^0-9]((\\\\d{1,3}\\\\.){3}\\\\d{1,3})$\"\n    )\n)",
     "legendFormat": "UnSchedulable"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum by (host_ip) (label_replace(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\", mountpoint !~\".*pod.*\"}, \"host_ip\", \"$1\", \"instance\", \"([0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+):.*\")) * on (host_ip) \n    label_replace(group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"}) by(node), \"host_ip\", \"$1\", \"node\",\".*[^0-9]((\\\\d{1,3}\\\\.){3}\\\\d{1,3})$\")\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Avg Boot Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  sum by (host_ip) (label_replace(time() - node_boot_time_seconds{}, \"host_ip\", \"$1\", \"instance\", \"([0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+):.*\")) * on (host_ip) \n    label_replace(group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"}) by(node), \"host_ip\", \"$1\", \"node\",\".*[^0-9]((\\\\d{1,3}\\\\.){3}\\\\d{1,3})$\")\n)"
    }
   ]
  },
  {
   "title": "Node Average Memory(%)",
   "type": "timeseries",
   "description": "Request: 根据Pod Request 值计算节点平均水位；\nLimit: 根据Pod Limit 值计算节点平均水位；\nUsage: 根据Pod 内存真实使用值计算节点平均水位；\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "avg(group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() (sum(kube_pod_container_resource_requests_memory_bytes)by(node)/sum(kube_node_status_allocatable{resource=\"memory\"})by(node)))",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Request",
     "method": "GET"
    },
    {
     "expr": "avg(group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() (sum(kube_pod_container_resource_limits_memory_bytes)by(node)/sum(kube_node_status_allocatable{resource=\"memory\"})by(node)))",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() (sum(container_memory_working_set_bytes{container!=\"\"})by(node)/sum(kube_node_status_allocatable{resource=\"memory\"})by(node)))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Node Average CPU(%)",
   "type": "timeseries",
   "description": "位于不同主机上所有容器的 Request/Usage/Limit 的CPU核数跟不同主机的总核数相除，计算节点级平均率。\n Request: 根据 Pod CPU Request 值计算CPU平均水位；\n Limit: 根据 Pod CPU Limit 值计算CPU平均水位；\n Usage: 根据 Pod CPU Usage 值计算节点平均水位。\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "avg(group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() (sum(kube_pod_container_resource_requests_cpu_cores)by(node)/sum(kube_node_status_allocatable{resource=\"cpu\"})by(node)))",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Request",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "avg(group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() (sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[1m]))by(node)/sum(kube_node_status_allocatable{resource=\"cpu\"})by(node)))",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Usage",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "avg(group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() (sum(kube_pod_container_resource_limits_cpu_cores)by(node)/sum(kube_node_status_allocatable{resource=\"cpu\"})by(node)))",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Limit",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Node Scheduler Resource Summary",
   "type": "table",
   "description": "基于节点调度资源占用进行统计。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() group(kube_node_info)by(node, internal_ip)"
    },
    {
     "expr": "group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right()  sum(kube_node_status_allocatable{resource=\"memory\"})by(node)"
    },
    {
     "expr": "group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() sum(kube_node_status_allocatable{resource=\"cpu\"})by(node)"
    },
    {
     "expr": "group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right()  sum(kube_node_status_allocatable{resource=\"pods\"})by(node)",
     "legendFormat": "Pod Allocatable"
    },
    {
     "expr": "group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() (sum((max(kube_pod_status_phase{phase=\"Running\"}) by (pod,namespace) > 0)  * on (pod,namespace) group_right() sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod,namespace,node))by(node)/sum(kube_node_status_allocatable{resource=\"memory\"})by(node))"
    },
    {
     "expr": "group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() (sum((max(kube_pod_status_phase{phase=\"Running\"}) by (pod,namespace) > 0)  * on (pod,namespace) group_right() sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod,namespace,node))by(node)/sum(kube_node_status_allocatable{resource=\"cpu\"})by(node))"
    },
    {
     "expr": "group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() (count((max(kube_pod_status_phase{phase=\"Running\"}) by (pod,namespace) > 0)  * on (pod,namespace) group_right() sum(kube_pod_info) by (pod,namespace,node))by(node)/sum(kube_node_status_allocatable{resource=\"pods\"})by(node))"
    },
    {
     "expr": "group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right()  sum((max(kube_pod_status_phase{phase=\"Running\"}) by (pod,namespace) > 0)  * on (pod,namespace) group_right() sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (pod,namespace,node))by(node)/sum(kube_node_status_allocatable{resource=\"memory\"})by(node)"
    },
    {
     "expr": "group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right()  sum((max(kube_pod_status_phase{phase=\"Running\"}) by (pod,namespace) > 0)  * on (pod,namespace) group_right() sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (pod,namespace,node))by(node)/sum(kube_node_status_allocatable{resource=\"cpu\"})by(node)"
    },
    {
     "expr": "group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() max(kube_node_spec_unschedulable) by (node)"
    },
    {
     "expr": "group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() sum(group(kube_pod_info) by (pod,namespace,node) * on (pod,namespace) group_left() sum(container_memory_working_set_bytes{container!=\"\",container!=\"POD\"}) by (pod,namespace)) by (node)/sum(kube_node_status_allocatable{resource=\"memory\"})by(node)"
    },
    {
     "expr": "group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) * on (node) group_right() sum(group(kube_pod_info) by (pod,namespace,node) * on (pod,namespace) group_left() sum(irate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[1m])) by (pod,namespace)) by (node)/sum(kube_node_status_allocatable{resource=\"cpu\"})by(node)"
    }
   ]
  },
  {
   "title": "Node Physical Resource Summary",
   "type": "table",
   "description": "基于节点物理资源占用进行统计。",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") + on (host_ip) group_right() label_replace(node_uname_info{},\"host_ip\",\"$1\",\"instance\",\"(.*):.*\") - 0",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "sum(label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(node_memory_MemTotal_bytes,\"host_ip\",\"$1\",\"instance\",\"(.*):.*\") - 0)by(instance)",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "sum(label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(count(node_cpu_seconds_total{mode='system'})by(instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(instance)",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "sum(label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(sum(time() - node_boot_time_seconds)by(instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(instance)",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "avg(label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(1-(node_filesystem_free_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}/node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(instance)",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "sum(label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by (instance)",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "sum(label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace((1 - (node_memory_MemAvailable_bytes{} / (node_memory_MemTotal_bytes{})))* 100,\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(instance)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "Memory Usage",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "sum(label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(max(irate(node_disk_read_bytes_total{}[5m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(instance)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "最大读取",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "sum(label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(max(irate(node_disk_written_bytes_total{}[5m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by (instance)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "最大写入",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "sum(label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(max(irate(node_network_receive_bytes_total{}[5m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(instance)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "下载带宽",
     "method": "GET"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "sum(label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(max(irate(node_network_transmit_bytes_total{}[5m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(instance)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "上传带宽",
     "method": "GET"
    },
    {
     "expr": "label_replace(group(group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (node, internal_ip),\"instance\",\"$1:9100\",\"internal_ip\",\"(.*)\")"
    }
   ]
  },
  {
   "title": "Memory Usage (Not Include Cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(node_memory_MemTotal_bytes-node_memory_Cached_bytes - node_memory_Buffers_bytes-node_memory_MemFree_bytes,\"host_ip\",\"$1\",\"instance\",\"(.*):.*\")",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{host_ip}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Memory Usage (Include Cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(node_memory_MemTotal_bytes-node_memory_MemFree_bytes,\"host_ip\",\"$1\",\"instance\",\"(.*):.*\")",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{host_ip}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\")",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{host_ip}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "CPU Load(1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "label_replace(sum(label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(max(node_load1) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(instance),\"host_ip\",\"$1\",\"instance\",\"(.*):(.*)\")",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{host_ip}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(1-node_filesystem_free_bytes{fstype=~\"ext4|xfs\"}/node_filesystem_size_bytes{fstype=~\"ext4|xfs\"},\"host_ip\",\"$1\",\"instance\",\"(.*):.*\")",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{host_ip}} MountPoint: {{mountpoint}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(max(irate(node_disk_read_bytes_total{}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\")",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{host_ip}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(max(irate(node_disk_written_bytes_total{}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\")",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{host_ip}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(max(irate(node_network_receive_bytes_total{}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\")",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{host_ip}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(max(irate(node_network_transmit_bytes_total{}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\")",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{host_ip}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Sockets Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "label_replace((group (group(kube_node_labels{label_alibabacloud_com_nodepool_id=\"$nodepool\"})by (node) + on (node) group_right() kube_node_info) by (internal_ip)), \"host_ip\", \"$1\", \"internal_ip\", \"(.*)\") * on(host_ip) group_right() label_replace(max(node_sockstat_TCP_alloc) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\")",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{host_ip}}",
     "method": "GET"
    }
   ]
  }
 ]
}